# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/hmo-crud

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # git pull
      - checkout

      # Docker setup
      #- setup_remote_docker:
          # save image layers and reuse unchanged layers on subsequent CircleCI runs
      #    docker_layer_caching: true
      - run:
          # use CircleCI environment variables for DockerHub username and password
          name: Login to DockerHub
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Compile, tests and package
      - run: gradle clean build
      - store_test_results:
          path: build/test-results/test

      # Build and push docker image to docker hub
      #- run: mvn clean compile jib:build -Dimage=zarinlo/springboot-api:$CIRCLE_BUILD_NUM
      #  CIRCLE_BUILD_NUM: CircleCI build-in environment variable
      - run: gradle jib --image=heliomolive/hmo-repository:hmo-crud