CREATE TABLE BEER(
    BEER_ID IDENTITY PRIMARY KEY, --identity: auto-incrementing long integer
    NAME VARCHAR2(100) NOT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT NOW(),
    UPDATE_DATE DATETIME NOT NULL DEFAULT NOW()
)